excluded:
  - .build
  - DerivedData

opt_in_rules:
  - contains_over_filter_count
  - empty_count
  - first_where
  - last_where
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool

line_length:
  warning: 120
  ignores_comments: true

trailing_comma:
  mandatory_comma: true

identifier_name:
  min_length: 1
